settings:
  - name: extended_simple
    pnpro: "net/extended_simple.PNPRO"
    customCPP: null
    parameters: null
    functions: null
    user_files: null
    sensitivity: FALSE
    calibration: FALSE
    SSA: FALSE
    index: 1

  - name: extended_CPP_Call
    pnpro: "net/extended_CPP_Call.PNPRO"
    customCPP: "functions/extended_general_functions.cpp"
    parameters: null
    functions: null
    user_files: null
    sensitivity: FALSE
    calibration: FALSE
    SSA: FALSE
    index: 2
    
  - name: reduced_simple
    pnpro: "net/reduced_simple.PNPRO"
    customCPP: null
    parameters: null
    functions: null
    user_files: null
    sensitivity: FALSE
    calibration: FALSE
    SSA: FALSE
    index: 3
    
  - name: reduced_noCPP_FromList
    pnpro: "net/reduced_noCPP_FromList.PNPRO"
    customCPP: null
    parameters: "input/iniData_reduced.csv"
    functions: "functions/rfunctions.R"
    user_files: "input/KineticsParameters"
    sensitivity: FALSE
    calibration: FALSE
    SSA: FALSE
    index: 4
    
  - name: reduced_CPP_Call
    pnpro: "net/reduced_CPP_Call.PNPRO"
    customCPP: "functions/reduced_general_functions.cpp"
    parameters: null
    functions: null
    user_files: null
    sensitivity: FALSE
    calibration: FALSE
    SSA: FALSE
    index: 5
    
  - name: reduced_CPP_Call_FromTable
    pnpro: "net/reduced_CPP_Call_FromTable.PNPRO"
    customCPP: "functions/reduced_general_functions_from.cpp"
    parameters: "input/iniData_reduced.csv"
    functions: "functions/rfunctions.R"
    user_files: "input/KineticsParameters.csv"
    sensitivity: FALSE
    calibration: FALSE
    SSA: FALSE
    index: 6
    
  - name: reduced_alternative
    pnpro: "net/reduced_alternative.PNPRO"
    customCPP: null
    parameters: "input/iniData_reduced_alternative.csv"
    functions: "functions/rfunctions.R"
    user_files: null
    sensitivity: FALSE
    calibration: FALSE
    SSA: FALSE
    index: 7
    
  - name: extended_sensitivity
    pnpro: "net/extended_sensitivity.PNPRO"
    customCPP: "functions/extended_general_functions.cpp"
    parameters: "input/iniData_exteded_sensitivity.csv"
    functions: "functions/rfunctions.R"
    user_files: null
    sensitivity: TRUE
    calibration: FALSE
    SSA: FALSE
    index: 8

  - name: extended_CPP_Call
    pnpro: "net/extended_CPP_Call.PNPRO"
    customCPP: "functions/extended_general_functions.cpp"
    parameters: null
    functions: null
    user_files: null
    sensitivity: FALSE
    calibration: FALSE
    SSA: TRUE
    index: 9
    
  - name: reduced_CPP_Call
    pnpro: "net/reduced_CPP_Call.PNPRO"
    customCPP: "functions/reduced_general_functions.cpp"
    parameters: null
    functions: null
    user_files: null
    sensitivity: FALSE
    calibration: FALSE
    SSA: TRUE
    index: 10
    
  - name: extended_All_General
    pnpro: "net/extended_All_General.PNPRO"
    customCPP: "functions/all_general_extended.cpp"
    parameters: null
    functions: null
    user_files: null
    sensitivity: FALSE
    calibration: FALSE
    SSA: TRUE
    index: 11

  - name: extended_calibration
    pnpro: "net/extended_calibration.PNPRO"
    customCPP: null
    parameters: "input/iniData_exteded_calibration.csv"
    functions: "functions/rfunctions.R"
    user_files: null
    sensitivity: FALSE
    calibration: TRUE
    SSA: FALSE
    index: 12
